# Generated by Django 3.2.8 on 2021-11-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_rename_ponto_funcionario_ponto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('reserva', models.BooleanField()),
                ('funcionario_cpf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.funcionario')),
            ],
        ),
    ]
