# Generated by Django 3.2.8 on 2021-11-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_ponto_id_funcionario_ponto'),
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ponto',
            new_name='Agendamentos',
        ),
    ]
