# Generated by Django 3.2.8 on 2021-11-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_rename_agendamentos_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='funcionario_cpf',
            new_name='funcionario',
        ),
    ]
