# Generated by Django 3.2.8 on 2021-11-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_rename_funcionario_cpf_agendamento_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='funcionario',
            new_name='funcionario_nome',
        ),
    ]
