# Generated by Django 3.2.8 on 2021-11-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_rename_funcionario_agendamento_funcionario_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='funcionario_nome',
            new_name='funcionario',
        ),
    ]
