# Generated by Django 3.2.8 on 2021-11-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_ponto_id_funcionario_ponto'),
        ('agendamentos', '0006_rename_funcionario_nome_agendamento_funcionario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('funcionario', 'data')},
        ),
    ]
