# Generated by Django 3.2.8 on 2021-11-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamento_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendamento',
            table='agendamento',
        ),
    ]
