# Generated by Django 3.2.8 on 2021-11-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_funcionario_table'),
        ('agendamentos', '0008_alter_agendamento_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='funcionario',
            new_name='funcionario_cpf',
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('funcionario_cpf', 'data')},
        ),
    ]
