# Generated by Django 3.2.8 on 2021-11-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_funcionario_linha'),
        ('agendamentos', '0009_auto_20211115_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentosFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_cpf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.funcionario')),
                ('unique_together', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendamentos.agendamento')),
            ],
            options={
                'db_table': 'agendamento_funcionarios',
            },
        ),
    ]
