# Generated by Django 3.2.8 on 2021-11-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_alter_agendamentosfuncionarios_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentosfuncionarios',
            name='funcionario_cpf',
        ),
        migrations.RemoveField(
            model_name='agendamentosfuncionarios',
            name='unique_together',
        ),
        migrations.AlterModelTable(
            name='agendamentosfuncionarios',
            table=None,
        ),
    ]
