# Generated by Django 3.2.8 on 2021-11-15 20:03

from django.db import migrations, models
import usuarios.help


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[usuarios.help.validate_CPF])),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=64)),
                ('ponto', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
