# Generated by Django 3.2.8 on 2021-11-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211115_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionarios',
            new_name='Funcionario',
        ),
    ]
