# Generated by Django 3.2.8 on 2021-11-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_funcionarios_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='ponto',
            new_name='ponto_id',
        ),
    ]
