# Generated by Django 3.2.8 on 2021-11-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_ponto_funcionario_ponto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='ponto_id',
            new_name='ponto',
        ),
    ]
