# Generated by Django 3.2.8 on 2021-11-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_ponto_id_funcionario_ponto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
    ]
