# Generated by Django 3.2.8 on 2021-11-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_funcionario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ponto',
            field=models.IntegerField(null=True),
        ),
    ]
